import type { WorkboardSnapshot } from './workboard.types'

export const mockWorkboardSnapshot: WorkboardSnapshot = {
  selectedRunId: 'run-convergence-sequential-review',
  trackerSources: [
    {
      id: 'linear-personal',
      type: 'linear',
      name: 'Linear personal',
      status: 'connected',
      scope: 'Team CONV + label convergence-loop',
      syncedAt: '2m ago',
      candidateCount: 4,
    },
    {
      id: 'jira-work',
      type: 'jira',
      name: 'Jira work',
      status: 'connected',
      scope: 'JQL: labels = convergence-loop',
      syncedAt: '5m ago',
      candidateCount: 3,
    },
    {
      id: 'jira-client',
      type: 'jira',
      name: 'Jira client sandbox',
      status: 'needs-auth',
      scope: 'API project + component Agent-ready',
      syncedAt: 'Needs login',
      candidateCount: 0,
    },
  ],
  candidates: [
    {
      id: 'issue-conv-209',
      trackerType: 'linear',
      trackerName: 'Linear personal',
      externalKey: 'CONV-209',
      title: 'Inline comments for risky turn file changes',
      projectName: 'convergence',
      mappingStatus: 'mapped',
      mappingRule: 'Linear team CONV -> convergence',
      state: 'ready',
      priority: 'high',
      labels: ['convergence-loop', 'loop-ready'],
      estimate: 'sequential reviewer',
      summary:
        'Ready issue created from exploration; acceptance criteria and changed-file examples are present.',
      updatedAt: '7m ago',
    },
    {
      id: 'issue-conv-213',
      trackerType: 'linear',
      trackerName: 'Linear personal',
      externalKey: 'CONV-213',
      title: 'Sandcastle auth mount smoke test',
      projectName: 'convergence',
      mappingStatus: 'mapped',
      mappingRule: 'Linear team CONV -> convergence',
      state: 'ready',
      priority: 'urgent',
      labels: ['convergence-loop', 'loop-ready'],
      estimate: 'simple loop',
      summary:
        'Small manual task to verify Claude and Codex subscription auth inside the Docker image.',
      updatedAt: '14m ago',
    },
    {
      id: 'issue-api-812',
      trackerType: 'jira',
      trackerName: 'Jira work',
      externalKey: 'API-812',
      title: 'Investigate billing migration read model',
      projectName: 'client-api',
      mappingStatus: 'project-not-ready',
      mappingRule: 'Jira project API + component Backend -> client-api',
      state: 'candidate',
      priority: 'medium',
      labels: ['convergence-loop', 'loop-candidate'],
      estimate: 'needs enrichment',
      summary:
        'Mapped to a project, but `.sandcastle/` and Docker auth mounts are not ready yet.',
      updatedAt: '22m ago',
    },
    {
      id: 'issue-web-44',
      trackerType: 'jira',
      trackerName: 'Jira work',
      externalKey: 'WEB-44',
      title: 'Audit onboarding empty states',
      projectName: null,
      mappingStatus: 'needs-mapping',
      mappingRule: 'No matching Jira component rule',
      state: 'ready',
      priority: 'low',
      labels: ['convergence-loop', 'loop-ready'],
      estimate: '1 agent',
      summary:
        'Tracker issue is loop-ready, but Convergence cannot route it to a local repo.',
      updatedAt: '31m ago',
    },
  ],
  projectGroups: [
    {
      id: 'project-convergence',
      projectId: 'project-convergence',
      projectName: 'convergence',
      repoPath: '/Users/marckraw/Projects/Private/convergence',
      trackerScopes: ['Linear team CONV', 'Jira labels = convergence-loop'],
      workflow: 'sequential reviewer',
      policy: 'review-heavy',
      sandcastleStatus: 'auth-risk',
      candidateIds: ['issue-conv-209', 'issue-conv-213'],
      selectedIssueIds: ['issue-conv-209'],
      checks: [
        {
          id: 'convergence-sandcastle-folder',
          label: '.sandcastle folder initialized',
          state: 'pass',
        },
        {
          id: 'convergence-prompts',
          label: 'implement/review prompts available',
          state: 'pass',
        },
        {
          id: 'convergence-auth-mounts',
          label: 'Claude/Codex auth mounts need smoke test',
          state: 'warn',
        },
      ],
    },
    {
      id: 'project-client-api',
      projectId: 'project-client-api',
      projectName: 'client-api',
      repoPath: '/Users/marckraw/Projects/Work/client-api',
      trackerScopes: ['Jira API project + Backend component'],
      workflow: 'simple loop',
      policy: 'safe smoke',
      sandcastleStatus: 'missing-sandcastle',
      candidateIds: ['issue-api-812'],
      selectedIssueIds: [],
      checks: [
        {
          id: 'client-api-sandcastle-folder',
          label: '.sandcastle folder missing',
          state: 'fail',
        },
        {
          id: 'client-api-docker',
          label: 'Docker Desktop available',
          state: 'pass',
        },
      ],
    },
  ],
  activeRuns: [
    {
      id: 'run-convergence-sequential-review',
      projectName: 'convergence',
      repoPath: '/Users/marckraw/Projects/Private/convergence',
      workflow: 'sequential reviewer',
      policy: 'review-heavy',
      status: 'running',
      branchStrategy: 'explicit branch',
      branchName: 'sandcastle/linear-conv-209-inline-comments',
      sandbox: 'Docker',
      progressPercent: 58,
      issueIds: ['issue-conv-209'],
      currentStage: 'implementer',
      startedAt: '13:42',
      logFilePath: '.sandcastle/logs/convergence/CONV-209-implementer.log',
      commits: ['abc1234'],
      summary:
        'Convergence started a controlled Sandcastle library run for one Linear issue. The implementer is writing the first patch before reviewer handoff.',
      stages: [
        {
          id: 'stage-conv-sync',
          role: 'sync',
          status: 'done',
          provider: 'Convergence',
          model: 'tracker adapter',
          iteration: 1,
          maxIterations: 1,
          logPreview: 'Linear issue CONV-209 normalized and mapped.',
          elapsed: '8s',
        },
        {
          id: 'stage-conv-planner',
          role: 'planner',
          status: 'done',
          provider: 'Claude Code',
          model: 'opus-4.6',
          iteration: 1,
          maxIterations: 1,
          logPreview: 'Selected sequential reviewer workflow and branch.',
          elapsed: '3m',
        },
        {
          id: 'stage-conv-implementer',
          role: 'implementer',
          status: 'running',
          provider: 'Codex',
          model: 'gpt-5.5 high',
          iteration: 3,
          maxIterations: 8,
          logPreview:
            'Tool call: npm run test:pure. Editing turn file change grouping.',
          elapsed: '19m',
        },
        {
          id: 'stage-conv-reviewer',
          role: 'reviewer',
          status: 'waiting',
          provider: 'Claude Code',
          model: 'sonnet-4.6',
          iteration: 0,
          maxIterations: 1,
          logPreview: 'Waiting for implementer commits.',
          elapsed: '0m',
        },
        {
          id: 'stage-conv-writeback',
          role: 'writeback',
          status: 'waiting',
          provider: 'Convergence',
          model: 'Linear adapter',
          iteration: 0,
          maxIterations: 1,
          logPreview: 'Will comment branch, commits, and review result.',
          elapsed: '0m',
        },
      ],
      recentEvents: [
        {
          id: 'event-conv-started',
          stageId: 'stage-conv-implementer',
          sequence: 1,
          type: 'lifecycle',
          message: 'Sandcastle implementer started in Docker.',
          createdAt: '13:42',
        },
        {
          id: 'event-conv-tool',
          stageId: 'stage-conv-implementer',
          sequence: 2,
          type: 'tool_call',
          message: 'npm run test:pure',
          createdAt: '13:51',
        },
      ],
    },
    {
      id: 'run-api-readiness',
      projectName: 'client-api',
      repoPath: '/Users/marckraw/Projects/Work/client-api',
      workflow: 'simple loop',
      policy: 'safe smoke',
      status: 'blocked',
      branchStrategy: 'explicit branch',
      branchName: 'sandcastle/jira-api-812-billing-read-model',
      sandbox: 'Docker',
      progressPercent: 18,
      issueIds: ['issue-api-812'],
      currentStage: 'planner',
      startedAt: '12:10',
      logFilePath: '.sandcastle/logs/convergence/API-812-readiness.log',
      commits: [],
      summary:
        'Run is blocked before agent execution because the mapped project does not have a project-owned `.sandcastle` workflow pack yet.',
      stages: [
        {
          id: 'stage-api-sync',
          role: 'sync',
          status: 'done',
          provider: 'Convergence',
          model: 'Jira adapter',
          iteration: 1,
          maxIterations: 1,
          logPreview: 'Jira issue API-812 normalized and mapped.',
          elapsed: '11s',
        },
        {
          id: 'stage-api-planner',
          role: 'planner',
          status: 'blocked',
          provider: 'Convergence',
          model: 'readiness check',
          iteration: 0,
          maxIterations: 1,
          logPreview: 'Missing .sandcastle/main.mts and implement prompt.',
          elapsed: '1m',
        },
      ],
      recentEvents: [
        {
          id: 'event-api-blocked',
          stageId: 'stage-api-planner',
          sequence: 1,
          type: 'lifecycle',
          message:
            'Run blocked before execution because the Sandcastle workflow pack is missing.',
          createdAt: '12:10',
        },
      ],
    },
  ],
}
