import type { ReactNode } from 'react'
import {
  Bot,
  CalendarDays,
  FileDiff,
  MessageSquare,
  MousePointerClick,
  Paperclip,
  Repeat2,
  Sparkles,
  TerminalSquare,
} from 'lucide-react'
import type { AnalyticsOverview } from '@/entities/analytics'
import { cn } from '@/shared/lib/cn.pure'
import { ChartGpuChart } from '@/shared/ui/chartgpu-chart.container'
import {
  buildConversationBalanceChartOptions,
  buildDailyActivityChartOptions,
  buildProviderUsageChartOptions,
  formatCompact,
  formatDateLabel,
  formatHour,
  formatInteger,
  formatSignedInteger,
  getHeatmapCount,
  getHeatmapLevel,
  hasUsageActivity,
  WEEKDAY_LABELS,
} from './analytics-insights.pure'

interface UsageTabProps {
  overview: AnalyticsOverview | null
  isLoading: boolean
}

interface MetricCard {
  label: string
  value: string
  detail?: string
  icon: ReactNode
}

const HEATMAP_HOURS = Array.from({ length: 24 }, (_, hour) => hour)
const STREAK_CELL_COUNT = 35
const CHART_HEIGHT = 320

export function UsageTab({ overview, isLoading }: UsageTabProps) {
  if (!overview) {
    if (isLoading) return renderLoadingState()

    return renderEmptyPanel({
      title: 'No analytics yet',
      description:
        'Start or continue a session and this section will fill in from local history.',
    })
  }

  const activityExists = hasUsageActivity(overview)
  const metricCards = buildMetricCards(overview)

  return (
    <div className="space-y-4">
      {!activityExists
        ? renderEmptyPanel({
            title: 'No usage in this range',
            description:
              'Try All time, or start a session and send a message to create local activity.',
          })
        : null}

      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {metricCards.map((card) => renderMetricCard(card))}
      </section>

      <section className="grid gap-4">
        {renderChartPanel({
          title: 'Daily activity',
          description: `${formatDateLabel(overview.range.startDate ?? overview.range.endDate)} to ${formatDateLabel(overview.range.endDate)}`,
          legend: [
            { label: 'User messages', colorClassName: 'bg-blue-600' },
            { label: 'Turns', colorClassName: 'bg-teal-500' },
          ],
          empty: !hasDailyActivity(overview),
          children: (
            <>
              <ChartGpuChart
                options={buildDailyActivityChartOptions(overview.dailyActivity)}
                height={CHART_HEIGHT}
                fallbackTitle="Daily chart unavailable"
                fallbackDescription="WebGPU is not available in this browser view. The totals and grids still work."
              />
              {renderChartRangeHint(
                formatDateLabel(
                  overview.range.startDate ?? overview.range.endDate,
                ),
                formatDateLabel(overview.range.endDate),
              )}
            </>
          ),
        })}

        {renderChartPanel({
          title: 'Provider usage',
          description: 'Sessions and completed turns by provider.',
          legend: [
            { label: 'Sessions', colorClassName: 'bg-violet-600' },
            { label: 'Turns', colorClassName: 'bg-amber-500' },
          ],
          empty: overview.providerUsage.length === 0,
          children: (
            <>
              <ChartGpuChart
                options={buildProviderUsageChartOptions(overview)}
                height={CHART_HEIGHT}
                fallbackTitle="Provider chart unavailable"
                fallbackDescription="WebGPU is not available in this browser view. Provider totals are listed below."
              />
              {renderProviderList(overview)}
            </>
          ),
        })}
      </section>

      <section className="grid gap-4 2xl:grid-cols-2">
        {renderProjectDistribution(overview)}
        {renderStreakCalendar(overview)}
      </section>

      <section className="grid gap-4">
        {renderHeatmap(overview)}
        {renderChartPanel({
          title: 'Conversation balance',
          description:
            'Approximate words written by you and generated by assistants.',
          legend: [
            { label: 'User words', colorClassName: 'bg-blue-600' },
            { label: 'Assistant words', colorClassName: 'bg-teal-500' },
          ],
          empty: !hasConversationBalance(overview),
          children: (
            <>
              <ChartGpuChart
                options={buildConversationBalanceChartOptions(overview)}
                height={CHART_HEIGHT}
                fallbackTitle="Balance chart unavailable"
                fallbackDescription="WebGPU is not available in this browser view. Word totals are still shown above."
              />
              {renderChartRangeHint(
                formatDateLabel(
                  overview.range.startDate ?? overview.range.endDate,
                ),
                formatDateLabel(overview.range.endDate),
              )}
            </>
          ),
        })}
      </section>
    </div>
  )
}

function renderLoadingState() {
  return (
    <div
      className="space-y-4"
      aria-label="Loading local analytics"
      aria-busy="true"
    >
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {Array.from({ length: 8 }, (_, index) => (
          <div
            key={index}
            className="min-w-0 rounded-lg border border-border bg-card/70 p-3"
          >
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0 flex-1 space-y-3">
                <div className="h-3 w-24 rounded bg-muted" />
                <div className="h-7 w-20 rounded bg-muted/80" />
                <div className="h-3 w-32 rounded bg-muted" />
              </div>
              <div className="h-8 w-8 rounded-md border border-border bg-muted" />
            </div>
          </div>
        ))}
      </section>

      <section className="grid gap-4">
        {Array.from({ length: 2 }, (_, index) => (
          <div
            key={index}
            className="min-w-0 rounded-lg border border-border bg-card/60 p-4"
          >
            <div className="mb-4 space-y-2">
              <div className="h-4 w-32 rounded bg-muted" />
              <div className="h-3 w-48 rounded bg-muted/80" />
            </div>
            <div className="h-[320px] rounded-lg bg-muted/50" />
          </div>
        ))}
      </section>
    </div>
  )
}

function renderMetricCard(card: MetricCard) {
  return (
    <article
      key={card.label}
      className="min-w-0 rounded-lg border border-border bg-card/70 p-3"
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0 flex-1">
          <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground break-words">
            {card.label}
          </p>
          <p className="mt-2 break-words text-2xl font-semibold">
            {card.value}
          </p>
          {card.detail ? (
            <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
              {card.detail}
            </p>
          ) : null}
        </div>
        <span className="rounded-md border border-border bg-background p-1.5 text-muted-foreground">
          {card.icon}
        </span>
      </div>
    </article>
  )
}

function renderChartPanel({
  title,
  description,
  legend,
  empty,
  children,
}: {
  title: string
  description: string
  legend?: Array<{ label: string; colorClassName: string }>
  empty: boolean
  children: ReactNode
}) {
  return (
    <section className="min-w-0 overflow-hidden rounded-lg border border-border bg-card/60 p-4">
      <div className="mb-3 flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
        <div>
          <h4 className="text-sm font-semibold">{title}</h4>
          <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
            {description}
          </p>
        </div>
        {legend ? renderChartLegend(legend) : null}
      </div>
      {empty
        ? renderEmptyPanel({
            title: 'No chart data',
            description:
              'This range does not have enough local activity for this view.',
            compact: true,
          })
        : children}
    </section>
  )
}

function renderChartLegend(
  items: Array<{ label: string; colorClassName: string }>,
) {
  return (
    <div className="flex shrink-0 flex-wrap gap-x-3 gap-y-1 text-xs text-muted-foreground">
      {items.map((item) => (
        <span key={item.label} className="inline-flex items-center gap-1.5">
          <span className={cn('h-2.5 w-2.5 rounded-sm', item.colorClassName)} />
          {item.label}
        </span>
      ))}
    </div>
  )
}

function renderChartRangeHint(left: string, right: string) {
  return (
    <div className="mt-2 flex items-center justify-between gap-3 text-[11px] text-muted-foreground">
      <span>{left}</span>
      <span>{right}</span>
    </div>
  )
}

function renderEmptyPanel({
  title,
  description,
  compact = false,
}: {
  title: string
  description: string
  compact?: boolean
}) {
  return (
    <div
      className={cn(
        'rounded-lg border border-dashed border-border bg-background/60 text-center',
        compact ? 'px-3 py-8' : 'px-4 py-10',
      )}
    >
      <p className="text-sm font-medium">{title}</p>
      <p className="mx-auto mt-1 max-w-md text-xs leading-relaxed text-muted-foreground">
        {description}
      </p>
    </div>
  )
}

function renderProviderList(overview: AnalyticsOverview) {
  const max = Math.max(
    ...overview.providerUsage.map((point) => point.turnsCompleted),
    1,
  )

  return (
    <div className="mt-3 space-y-2">
      {overview.providerUsage.slice(0, 5).map((point) => (
        <div key={point.providerId} className="space-y-1">
          <div className="flex items-center justify-between gap-3 text-xs">
            <span className="truncate font-medium">{point.providerName}</span>
            <span className="shrink-0 text-muted-foreground">
              {formatInteger(point.turnsCompleted)} turns
            </span>
          </div>
          <div className="h-1.5 overflow-hidden rounded-full bg-muted">
            <div
              className="h-full rounded-full bg-violet-500"
              style={{ width: `${(point.turnsCompleted / max) * 100}%` }}
            />
          </div>
        </div>
      ))}
    </div>
  )
}

function renderProjectDistribution(overview: AnalyticsOverview) {
  const max = Math.max(
    ...overview.projectUsage.map((point) => point.turnsCompleted),
    1,
  )

  return (
    <section className="min-w-0 rounded-lg border border-border bg-card/60 p-4">
      <div className="mb-4">
        <h4 className="text-sm font-semibold">Project distribution</h4>
        <p className="mt-1 text-xs text-muted-foreground">
          Top projects by completed turns.
        </p>
      </div>

      {overview.projectUsage.length === 0 ? (
        renderEmptyPanel({
          title: 'No project activity',
          description:
            'Project usage appears after local sessions are associated with projects.',
          compact: true,
        })
      ) : (
        <div className="space-y-3">
          {overview.projectUsage.slice(0, 7).map((point, index) => (
            <div
              key={point.projectId}
              className="grid grid-cols-[1fr_auto] gap-3"
            >
              <div className="min-w-0">
                <div className="flex items-center gap-2">
                  <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-md bg-blue-500/10 text-[11px] font-semibold text-blue-700 dark:text-blue-200">
                    {index + 1}
                  </span>
                  <span className="truncate text-sm font-medium">
                    {point.projectName}
                  </span>
                </div>
                <div className="mt-2 h-2 overflow-hidden rounded-full bg-muted">
                  <div
                    className="h-full rounded-full bg-blue-500"
                    style={{ width: `${(point.turnsCompleted / max) * 100}%` }}
                  />
                </div>
              </div>
              <div className="text-right text-xs text-muted-foreground">
                <p>{formatInteger(point.turnsCompleted)} turns</p>
                <p>{formatInteger(point.sessionsCreated)} sessions</p>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  )
}

function renderStreakCalendar(overview: AnalyticsOverview) {
  const days = buildRecentDays(overview.range.endDate, STREAK_CELL_COUNT)
  const activeDays = new Set(overview.streaks.activeDays)
  const currentMarker =
    overview.streaks.current > 0 ? findLatestActiveDay(activeDays) : null

  return (
    <section className="min-w-0 rounded-lg border border-border bg-card/60 p-4">
      <div className="mb-4 flex items-start justify-between gap-3">
        <div>
          <h4 className="text-sm font-semibold">Streak calendar</h4>
          <p className="mt-1 text-xs text-muted-foreground">
            Active days from local messages, turns, or sessions.
          </p>
        </div>
        <div className="shrink-0 text-right">
          <p className="text-lg font-semibold">
            {formatInteger(overview.streaks.current)}
          </p>
          <p className="text-[11px] text-muted-foreground">current</p>
        </div>
      </div>

      <div className="grid grid-cols-7 gap-1.5" aria-label="Recent activity">
        {days.map((day) => {
          const active = activeDays.has(day)
          const isCurrent = day === currentMarker
          return (
            <div
              key={day}
              title={`${formatDateLabel(day)}${active ? ': active' : ''}`}
              className={cn(
                'aspect-square rounded-md border',
                active
                  ? 'border-teal-500/40 bg-teal-500'
                  : 'border-border bg-muted/45',
                isCurrent &&
                  'ring-2 ring-amber-400 ring-offset-1 ring-offset-background',
              )}
            />
          )
        })}
      </div>

      <div className="mt-3 flex items-center justify-between text-xs text-muted-foreground">
        <span>Longest streak: {formatInteger(overview.streaks.longest)}</span>
        <span>Last {STREAK_CELL_COUNT} days</span>
      </div>
    </section>
  )
}

function renderHeatmap(overview: AnalyticsOverview) {
  const max = Math.max(
    ...overview.weekdayHourActivity.map((point) => point.count),
    0,
  )

  return (
    <section className="min-w-0 rounded-lg border border-border bg-card/60 p-4">
      <div className="mb-4">
        <h4 className="text-sm font-semibold">Time-of-day heatmap</h4>
        <p className="mt-1 text-xs text-muted-foreground">
          Local activity by weekday and hour.
        </p>
      </div>

      {max === 0 ? (
        renderEmptyPanel({
          title: 'No hourly pattern',
          description:
            'Activity by hour appears after messages, turns, or sessions are present.',
          compact: true,
        })
      ) : (
        <div className="overflow-x-auto pb-1">
          <div className="grid min-w-[540px] grid-cols-[2.25rem_repeat(24,minmax(0,1fr))] gap-1">
            <div />
            {HEATMAP_HOURS.map((hour) => (
              <div
                key={hour}
                className="text-center text-[10px] text-muted-foreground"
              >
                {hour % 6 === 0 ? formatHour(hour) : ''}
              </div>
            ))}
            {WEEKDAY_LABELS.map((label, weekday) => (
              <div key={label} className="contents">
                {renderHeatmapRow({ label, weekday, overview, max })}
              </div>
            ))}
          </div>
        </div>
      )}
    </section>
  )
}

function renderHeatmapRow({
  label,
  weekday,
  overview,
  max,
}: {
  label: string
  weekday: number
  overview: AnalyticsOverview
  max: number
}) {
  return (
    <>
      <div className="flex items-center text-[11px] text-muted-foreground">
        {label}
      </div>
      {HEATMAP_HOURS.map((hour) => {
        const count = getHeatmapCount(
          overview.weekdayHourActivity,
          weekday,
          hour,
        )
        const level = getHeatmapLevel(count, max)
        return (
          <div
            key={`${weekday}-${hour}`}
            title={`${label} ${formatHour(hour)}: ${formatInteger(count)}`}
            className={cn(
              'aspect-square rounded-[4px] border border-border/50',
              level === 0 && 'bg-muted/40',
              level === 1 && 'bg-teal-200/60 dark:bg-teal-950',
              level === 2 && 'bg-teal-400/70 dark:bg-teal-800',
              level === 3 && 'bg-teal-600/80 dark:bg-teal-600',
              level === 4 && 'bg-amber-500/90 dark:bg-amber-500',
            )}
          />
        )
      })}
    </>
  )
}

function buildMetricCards(overview: AnalyticsOverview): MetricCard[] {
  const { totals, streaks } = overview

  return [
    {
      label: 'User messages',
      value: formatCompact(totals.userMessages),
      detail: `${formatCompact(totals.userWords)} words written`,
      icon: <MessageSquare className="size-4" />,
    },
    {
      label: 'Assistant messages',
      value: formatCompact(totals.assistantMessages),
      detail: `${formatCompact(totals.assistantWords)} words generated`,
      icon: <Bot className="size-4" />,
    },
    {
      label: 'Sessions',
      value: formatCompact(totals.sessionsCreated),
      detail: `${formatCompact(totals.turnsCompleted)} turns completed`,
      icon: <Repeat2 className="size-4" />,
    },
    {
      label: 'Files changed',
      value: formatCompact(totals.filesChanged),
      detail: `${formatSignedInteger(totals.linesAdded)} / ${formatSignedInteger(-totals.linesDeleted)} lines`,
      icon: <FileDiff className="size-4" />,
    },
    {
      label: 'Approvals',
      value: formatCompact(totals.approvalRequests),
      detail: `${formatCompact(totals.inputRequests)} input requests`,
      icon: <MousePointerClick className="size-4" />,
    },
    {
      label: 'Attachments',
      value: formatCompact(totals.attachmentsSent),
      detail: `${formatCompact(totals.toolCalls)} tool calls`,
      icon: <Paperclip className="size-4" />,
    },
    {
      label: 'Current streak',
      value: `${formatInteger(streaks.current)}d`,
      detail: `${formatInteger(streaks.longest)}d longest`,
      icon: <CalendarDays className="size-4" />,
    },
    {
      label: 'Run health',
      value:
        totals.failedSessions > 0
          ? formatCompact(totals.failedSessions)
          : 'Clear',
      detail:
        totals.failedSessions > 0 ? 'failed sessions' : 'no failed sessions',
      icon:
        totals.failedSessions > 0 ? (
          <TerminalSquare className="size-4" />
        ) : (
          <Sparkles className="size-4" />
        ),
    },
  ]
}

function hasDailyActivity(overview: AnalyticsOverview): boolean {
  return overview.dailyActivity.some(
    (point) =>
      point.userMessages +
        point.assistantMessages +
        point.sessionsCreated +
        point.turnsCompleted >
      0,
  )
}

function hasConversationBalance(overview: AnalyticsOverview): boolean {
  return overview.conversationBalance.some(
    (point) => point.userWords + point.assistantWords > 0,
  )
}

function buildRecentDays(endDate: string, count: number): string[] {
  const end = new Date(`${endDate}T00:00:00`)
  return Array.from({ length: count }, (_, index) => {
    const date = new Date(end)
    date.setDate(end.getDate() - (count - 1 - index))
    return toDateKey(date)
  })
}

function findLatestActiveDay(activeDays: Set<string>): string | null {
  return [...activeDays].sort().at(-1) ?? null
}

function toDateKey(date: Date): string {
  const year = date.getFullYear()
  const month = `${date.getMonth() + 1}`.padStart(2, '0')
  const day = `${date.getDate()}`.padStart(2, '0')
  return `${year}-${month}-${day}`
}
