/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as CodeReviewRouteImport } from './routes/code/review'
import { Route as CodeSessionsNewRouteImport } from './routes/code/sessions/new'
import { Route as CodeSessionsSessionIdRouteImport } from './routes/code/sessions/$sessionId'
import { Route as ChatSpaceSpaceIdRouteImport } from './routes/chat/space/$spaceId'
import { Route as ChatSessionSessionIdRouteImport } from './routes/chat/session/$sessionId'

const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeReviewRoute = CodeReviewRouteImport.update({
  id: '/code/review',
  path: '/code/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSessionsNewRoute = CodeSessionsNewRouteImport.update({
  id: '/code/sessions/new',
  path: '/code/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeSessionsSessionIdRoute = CodeSessionsSessionIdRouteImport.update({
  id: '/code/sessions/$sessionId',
  path: '/code/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSpaceSpaceIdRoute = ChatSpaceSpaceIdRouteImport.update({
  id: '/chat/space/$spaceId',
  path: '/chat/space/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionSessionIdRoute = ChatSessionSessionIdRouteImport.update({
  id: '/chat/session/$sessionId',
  path: '/chat/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mission-control': typeof MissionControlRoute
  '/code/review': typeof CodeReviewRoute
  '/chat/': typeof ChatIndexRoute
  '/chat/session/$sessionId': typeof ChatSessionSessionIdRoute
  '/chat/space/$spaceId': typeof ChatSpaceSpaceIdRoute
  '/code/sessions/$sessionId': typeof CodeSessionsSessionIdRoute
  '/code/sessions/new': typeof CodeSessionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mission-control': typeof MissionControlRoute
  '/code/review': typeof CodeReviewRoute
  '/chat': typeof ChatIndexRoute
  '/chat/session/$sessionId': typeof ChatSessionSessionIdRoute
  '/chat/space/$spaceId': typeof ChatSpaceSpaceIdRoute
  '/code/sessions/$sessionId': typeof CodeSessionsSessionIdRoute
  '/code/sessions/new': typeof CodeSessionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mission-control': typeof MissionControlRoute
  '/code/review': typeof CodeReviewRoute
  '/chat/': typeof ChatIndexRoute
  '/chat/session/$sessionId': typeof ChatSessionSessionIdRoute
  '/chat/space/$spaceId': typeof ChatSpaceSpaceIdRoute
  '/code/sessions/$sessionId': typeof CodeSessionsSessionIdRoute
  '/code/sessions/new': typeof CodeSessionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mission-control'
    | '/code/review'
    | '/chat/'
    | '/chat/session/$sessionId'
    | '/chat/space/$spaceId'
    | '/code/sessions/$sessionId'
    | '/code/sessions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mission-control'
    | '/code/review'
    | '/chat'
    | '/chat/session/$sessionId'
    | '/chat/space/$spaceId'
    | '/code/sessions/$sessionId'
    | '/code/sessions/new'
  id:
    | '__root__'
    | '/'
    | '/mission-control'
    | '/code/review'
    | '/chat/'
    | '/chat/session/$sessionId'
    | '/chat/space/$spaceId'
    | '/code/sessions/$sessionId'
    | '/code/sessions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissionControlRoute: typeof MissionControlRoute
  CodeReviewRoute: typeof CodeReviewRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatSessionSessionIdRoute: typeof ChatSessionSessionIdRoute
  ChatSpaceSpaceIdRoute: typeof ChatSpaceSpaceIdRoute
  CodeSessionsSessionIdRoute: typeof CodeSessionsSessionIdRoute
  CodeSessionsNewRoute: typeof CodeSessionsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/review': {
      id: '/code/review'
      path: '/code/review'
      fullPath: '/code/review'
      preLoaderRoute: typeof CodeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/sessions/new': {
      id: '/code/sessions/new'
      path: '/code/sessions/new'
      fullPath: '/code/sessions/new'
      preLoaderRoute: typeof CodeSessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code/sessions/$sessionId': {
      id: '/code/sessions/$sessionId'
      path: '/code/sessions/$sessionId'
      fullPath: '/code/sessions/$sessionId'
      preLoaderRoute: typeof CodeSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/space/$spaceId': {
      id: '/chat/space/$spaceId'
      path: '/chat/space/$spaceId'
      fullPath: '/chat/space/$spaceId'
      preLoaderRoute: typeof ChatSpaceSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/session/$sessionId': {
      id: '/chat/session/$sessionId'
      path: '/chat/session/$sessionId'
      fullPath: '/chat/session/$sessionId'
      preLoaderRoute: typeof ChatSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissionControlRoute: MissionControlRoute,
  CodeReviewRoute: CodeReviewRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatSessionSessionIdRoute: ChatSessionSessionIdRoute,
  ChatSpaceSpaceIdRoute: ChatSpaceSpaceIdRoute,
  CodeSessionsSessionIdRoute: CodeSessionsSessionIdRoute,
  CodeSessionsNewRoute: CodeSessionsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
