import type { ReactNode } from 'react'
import {
  Bot,
  CalendarDays,
  FileDiff,
  MessageSquare,
  MousePointerClick,
  Paperclip,
  Repeat2,
  Sparkles,
  TerminalSquare,
} from 'lucide-react'
import type { AnalyticsOverview } from '@/entities/analytics'
import { Card, cn, EmptyState, SectionLabel } from '@convergence/ui'
import { ChartGpuChart } from '@/shared/ui/chartgpu-chart.container'
import {
  buildConversationBalanceChartOptions,
  buildDailyActivityChartOptions,
  formatCompact,
  formatDateLabel,
  formatHour,
  formatInteger,
  formatSignedInteger,
  getHeatmapCount,
  getHeatmapLevel,
  hasUsageActivity,
  WEEKDAY_LABELS_MONDAY_FIRST,
} from './analytics-insights.pure'
import {
  cardDetail,
  cardTop,
  heatFill,
  iconChip,
  seriesFill,
  type SeriesIndex,
  skeletonBar,
} from './analytics-insights.styles'

interface UsageTabProps {
  overview: AnalyticsOverview | null
  isLoading: boolean
}

interface MetricCard {
  label: string
  value: string
  detail?: string
  icon: ReactNode
}

const HEATMAP_HOURS = Array.from({ length: 24 }, (_, hour) => hour)
const STREAK_CELL_COUNT = 35
const CHART_HEIGHT = 320

export function UsageTab({ overview, isLoading }: UsageTabProps) {
  if (!overview) {
    if (isLoading) return renderLoadingState()

    return renderEmptyPanel({
      title: 'No analytics yet',
      description:
        'Start or continue a session and this section will fill in from local history.',
    })
  }

  const activityExists = hasUsageActivity(overview)
  const metricCards = buildMetricCards(overview)

  return (
    <div className="space-y-4">
      {!activityExists
        ? renderEmptyPanel({
            title: 'No usage in this range',
            description:
              'Try All time, or start a session and send a message to create local activity.',
          })
        : null}

      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {metricCards.map((card) => renderMetricCard(card))}
      </section>

      <section className="grid gap-4">
        {renderChartPanel({
          title: 'Daily activity',
          description: `${formatDateLabel(overview.range.startDate ?? overview.range.endDate)} to ${formatDateLabel(overview.range.endDate)}`,
          legend: [
            { label: 'User messages', series: 1 },
            { label: 'Turns', series: 2 },
          ],
          empty: !hasDailyActivity(overview),
          children: (
            <>
              <ChartGpuChart
                options={buildDailyActivityChartOptions(overview.dailyActivity)}
                height={CHART_HEIGHT}
                fallbackTitle="Daily chart unavailable"
                fallbackDescription="WebGPU is not available in this browser view. The totals and grids still work."
              />
              {renderChartRangeHint(
                formatDateLabel(
                  overview.range.startDate ?? overview.range.endDate,
                ),
                formatDateLabel(overview.range.endDate),
              )}
            </>
          ),
        })}

        {renderChartPanel({
          title: 'Provider usage',
          description: 'Sessions and completed turns by provider.',
          legend: [
            { label: 'Sessions', series: 4 },
            { label: 'Turns', series: 3 },
          ],
          empty: overview.providerUsage.length === 0,
          children: renderProviderUsageBars(overview),
        })}

        {renderChartPanel({
          title: 'Model usage',
          description: 'Sessions and completed turns by model.',
          legend: [
            { label: 'Sessions', series: 1 },
            { label: 'Turns', series: 2 },
          ],
          empty: overview.modelUsage.length === 0,
          children: renderModelUsageBars(overview),
        })}
      </section>

      <section className="grid gap-4 2xl:grid-cols-2">
        {renderProjectDistribution(overview)}
        {renderStreakCalendar(overview)}
      </section>

      <section className="grid gap-4">
        {renderHeatmap(overview)}
        {renderChartPanel({
          title: 'Conversation balance',
          description:
            'Approximate words written by you and generated by assistants.',
          legend: [
            { label: 'User words', series: 1 },
            { label: 'Assistant words', series: 2 },
          ],
          empty: !hasConversationBalance(overview),
          children: (
            <>
              <ChartGpuChart
                options={buildConversationBalanceChartOptions(overview)}
                height={CHART_HEIGHT}
                fallbackTitle="Balance chart unavailable"
                fallbackDescription="WebGPU is not available in this browser view. Word totals are still shown above."
              />
              {renderChartRangeHint(
                formatDateLabel(
                  overview.range.startDate ?? overview.range.endDate,
                ),
                formatDateLabel(overview.range.endDate),
              )}
            </>
          ),
        })}
      </section>
    </div>
  )
}

/** A skeleton of the tab while it loads: a status, so it is announced. */
function renderLoadingState() {
  return (
    <div
      role="status"
      className="space-y-4"
      aria-label="Loading local analytics"
      aria-busy="true"
    >
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {Array.from({ length: 8 }, (_, index) => (
          <Card key={index} className="min-w-0">
            <div className={cardTop}>
              <div className="min-w-0 flex-1 space-y-3">
                <div className={cn(skeletonBar, 'h-3 w-24')} />
                <div className={cn(skeletonBar, 'h-7 w-20')} />
                <div className={cn(skeletonBar, 'h-3 w-32')} />
              </div>
              <div className={cn(skeletonBar, 'size-8 rounded-md')} />
            </div>
          </Card>
        ))}
      </section>

      <section className="grid gap-4">
        {Array.from({ length: 2 }, (_, index) => (
          <Card key={index} padding="md" className="min-w-0">
            <div className="mb-4 space-y-2">
              <div className={cn(skeletonBar, 'h-4 w-32')} />
              <div className={cn(skeletonBar, 'h-3 w-48')} />
            </div>
            <div className={cn(skeletonBar, 'h-80 rounded-lg')} />
          </Card>
        ))}
      </section>
    </div>
  )
}

function renderMetricCard(card: MetricCard) {
  return (
    <Card key={card.label} render={<article />} className="min-w-0">
      <div className={cardTop}>
        <div className="min-w-0 flex-1">
          <SectionLabel className="wrap-break-word">{card.label}</SectionLabel>
          <p className="mt-2 text-2xl font-semibold wrap-break-word">
            {card.value}
          </p>
          {card.detail ? <p className={cardDetail}>{card.detail}</p> : null}
        </div>
        <span aria-hidden className={iconChip}>
          {card.icon}
        </span>
      </div>
    </Card>
  )
}

function renderChartPanel({
  title,
  description,
  legend,
  empty,
  children,
}: {
  title: string
  description: string
  legend?: LegendItem[]
  empty: boolean
  children: ReactNode
}) {
  return (
    <Card render={<section />} padding="md" className="min-w-0 overflow-hidden">
      <div className="mb-3 flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
        <div>
          <h4 className="text-sm font-semibold">{title}</h4>
          <p className={cardDetail}>{description}</p>
        </div>
        {legend ? renderChartLegend(legend) : null}
      </div>
      {empty
        ? renderEmptyPanel({
            title: 'No chart data',
            description:
              'This range does not have enough local activity for this view.',
          })
        : children}
    </Card>
  )
}

interface LegendItem {
  label: string
  /** The series it names, in the chart's colour. */
  series: SeriesIndex
}

function renderChartLegend(items: LegendItem[]) {
  return (
    <div className="flex shrink-0 flex-wrap gap-x-3 gap-y-1 text-xs text-ink-muted">
      {items.map((item) => (
        <span key={item.label} className="inline-flex items-center gap-1.5">
          <span
            aria-hidden
            className={cn('size-2.5 rounded-sm', seriesFill[item.series])}
          />
          {item.label}
        </span>
      ))}
    </div>
  )
}

function renderChartRangeHint(left: string, right: string) {
  return (
    <div className="mt-2 flex items-center justify-between gap-3 text-2xs text-ink-muted">
      <span>{left}</span>
      <span>{right}</span>
    </div>
  )
}

/** Nothing to draw here: the kit's empty box (DLG-18). */
function renderEmptyPanel({
  title,
  description,
}: {
  title: string
  description: string
}) {
  return <EmptyState title={title} detail={description} />
}

function renderProviderUsageBars(overview: AnalyticsOverview) {
  const points = overview.providerUsage.slice(0, 8)
  const max = Math.max(
    ...points.map((point) =>
      Math.max(point.sessionsCreated, point.turnsCompleted),
    ),
    1,
  )

  return (
    <div className="space-y-3">
      {points.map((point) => (
        <div key={point.providerId} className="flex items-center gap-3">
          <span className="w-36 shrink-0 truncate text-sm font-medium">
            {point.providerName}
          </span>
          <div className="min-w-0 flex-1 space-y-1.5">
            {renderUsageRow({
              label: 'Sessions',
              value: point.sessionsCreated,
              max,
              series: 4,
            })}
            {renderUsageRow({
              label: 'Turns',
              value: point.turnsCompleted,
              max,
              series: 3,
            })}
          </div>
        </div>
      ))}
    </div>
  )
}

/**
 * One bar of a bar chart: its words and its number are the text, so the bar
 * itself is drawn for the eye only (DLG-25: not a meter, nothing is used up).
 */
function renderUsageRow({
  label,
  value,
  max,
  series,
}: {
  label: string
  value: number
  max: number
  series: SeriesIndex
}) {
  return (
    <div className="flex items-center gap-2 text-2xs text-ink-muted">
      <span className="w-14 shrink-0">{label}</span>
      {renderBar(value, max, series)}
      <span className="w-14 shrink-0 text-right font-medium text-ink">
        {formatInteger(value)}
      </span>
    </div>
  )
}

/** A bar's length against the longest, in its series' colour. */
function renderBar(value: number, max: number, series: SeriesIndex) {
  const widthPct = max > 0 ? (value / max) * 100 : 0
  return (
    <div
      aria-hidden
      className="h-2 min-w-0 flex-1 overflow-hidden rounded-full bg-surface-muted"
    >
      <div
        className={cn('h-full rounded-full', seriesFill[series])}
        style={{ width: `${widthPct}%` }}
      />
    </div>
  )
}

function renderModelUsageBars(overview: AnalyticsOverview) {
  const points = overview.modelUsage.slice(0, 8)
  const max = Math.max(
    ...points.map((point) =>
      Math.max(point.sessionsCreated, point.turnsCompleted),
    ),
    1,
  )

  return (
    <div className="space-y-3">
      {points.map((point) => (
        <div key={point.modelId} className="flex items-center gap-3">
          <span className="w-36 shrink-0 truncate text-sm font-medium">
            {point.modelLabel}
          </span>
          <div className="min-w-0 flex-1 space-y-1.5">
            {renderUsageRow({
              label: 'Sessions',
              value: point.sessionsCreated,
              max,
              series: 1,
            })}
            {renderUsageRow({
              label: 'Turns',
              value: point.turnsCompleted,
              max,
              series: 2,
            })}
          </div>
        </div>
      ))}
    </div>
  )
}

function renderProjectDistribution(overview: AnalyticsOverview) {
  const max = Math.max(
    ...overview.projectUsage.map((point) => point.turnsCompleted),
    1,
  )

  return (
    <Card render={<section />} padding="md" className="min-w-0">
      <div className="mb-4">
        <h4 className="text-sm font-semibold">Project distribution</h4>
        <p className="mt-1 text-xs text-ink-muted">
          Top projects by completed turns.
        </p>
      </div>

      {overview.projectUsage.length === 0 ? (
        renderEmptyPanel({
          title: 'No project activity',
          description:
            'Project usage appears after local sessions are associated with projects.',
        })
      ) : (
        <ol className="space-y-3">
          {overview.projectUsage.slice(0, 7).map((point, index) => (
            <li key={point.projectId} className="flex gap-3">
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <span
                    aria-hidden
                    className="flex size-5 shrink-0 items-center justify-center rounded-md bg-surface-muted text-2xs font-semibold text-ink-muted"
                  >
                    {index + 1}
                  </span>
                  <span className="truncate text-sm font-medium">
                    {point.projectName}
                  </span>
                </div>
                <div className="mt-2 flex">
                  {renderBar(point.turnsCompleted, max, 1)}
                </div>
              </div>
              <div className="shrink-0 text-right text-xs text-ink-muted">
                <p>{formatInteger(point.turnsCompleted)} turns</p>
                <p>{formatInteger(point.sessionsCreated)} sessions</p>
              </div>
            </li>
          ))}
        </ol>
      )}
    </Card>
  )
}

function renderStreakCalendar(overview: AnalyticsOverview) {
  const days = buildRecentDays(overview.range.endDate, STREAK_CELL_COUNT)
  const activeDays = new Set(overview.streaks.activeDays)
  const currentMarker =
    overview.streaks.current > 0 ? findLatestActiveDay(activeDays) : null

  return (
    <Card render={<section />} padding="md" className="min-w-0">
      <div className="mb-4 flex items-start justify-between gap-3">
        <div>
          <h4 className="text-sm font-semibold">Streak calendar</h4>
          <p className="mt-1 text-xs text-ink-muted">
            Active days from local messages, turns, or sessions.
          </p>
        </div>
        <div className="shrink-0 text-right">
          <p className="text-lg font-semibold">
            {formatInteger(overview.streaks.current)}
          </p>
          <p className="text-2xs text-ink-muted">current</p>
        </div>
      </div>

      <div
        role="group"
        className="grid grid-cols-7 gap-1.5"
        aria-label="Recent activity"
      >
        {/* Weekday header row (Monday first) */}
        {WEEKDAY_LABELS_MONDAY_FIRST.map((label) => (
          <div
            key={label}
            className="flex items-center justify-center text-3xs font-medium text-ink-muted"
          >
            {label}
          </div>
        ))}
        {days.map((day) => {
          const active = activeDays.has(day)
          const isCurrent = day === currentMarker
          return (
            <div
              key={day}
              title={`${formatDateLabel(day)}${active ? ': active' : ''}`}
              className={cn(
                'aspect-square rounded-md border',
                active
                  ? 'border-chart-2/40 bg-chart-2'
                  : 'border-line bg-surface-muted/45',
                isCurrent &&
                  'ring-2 ring-chart-3 ring-offset-1 ring-offset-canvas',
              )}
            />
          )
        })}
      </div>

      <div className="mt-3 flex items-center justify-between text-xs text-ink-muted">
        <span>Longest streak: {formatInteger(overview.streaks.longest)}</span>
        <span>Last {STREAK_CELL_COUNT} days</span>
      </div>
    </Card>
  )
}

function renderHeatmap(overview: AnalyticsOverview) {
  const max = Math.max(
    ...overview.weekdayHourActivity.map((point) => point.count),
    0,
  )

  return (
    <Card render={<section />} padding="md" className="min-w-0">
      <div className="mb-4">
        <h4 className="text-sm font-semibold">Time-of-day heatmap</h4>
        <p className="mt-1 text-xs text-ink-muted">
          Local activity by weekday and hour.
        </p>
      </div>

      {max === 0 ? (
        renderEmptyPanel({
          title: 'No hourly pattern',
          description:
            'Activity by hour appears after messages, turns, or sessions are present.',
        })
      ) : (
        <div className="overflow-x-auto pb-1">
          <div className="min-w-135 space-y-1">
            <div className="flex gap-1">
              <div className="w-9 shrink-0" />
              <div className="grid flex-1 grid-cols-24 gap-1">
                {HEATMAP_HOURS.map((hour) => (
                  <div
                    key={hour}
                    className="text-center text-3xs text-ink-muted"
                  >
                    {hour % 6 === 0 ? formatHour(hour) : ''}
                  </div>
                ))}
              </div>
            </div>
            {/* Weekday data rows (Monday first) */}
            {WEEKDAY_LABELS_MONDAY_FIRST.map((label, index) => {
              // Map Monday-first index to weekday number (0=Sunday, 1=Monday, etc.)
              const weekday = index === 6 ? 0 : index + 1
              return (
                <div key={label} className="flex gap-1">
                  {renderHeatmapRow({ label, weekday, overview, max })}
                </div>
              )
            })}
          </div>
        </div>
      )}
    </Card>
  )
}

function renderHeatmapRow({
  label,
  weekday,
  overview,
  max,
}: {
  label: string
  weekday: number
  overview: AnalyticsOverview
  max: number
}) {
  return (
    <>
      <div className="flex w-9 shrink-0 items-center text-2xs text-ink-muted">
        {label}
      </div>
      <div className="grid flex-1 grid-cols-24 gap-1">
        {HEATMAP_HOURS.map((hour) => {
          const count = getHeatmapCount(
            overview.weekdayHourActivity,
            weekday,
            hour,
          )
          return (
            <div
              key={`${weekday}-${hour}`}
              title={`${label} ${formatHour(hour)}: ${formatInteger(count)}`}
              className={cn(
                'aspect-square rounded-sm border border-line-soft',
                heatFill[getHeatmapLevel(count, max)],
              )}
            />
          )
        })}
      </div>
    </>
  )
}

function buildMetricCards(overview: AnalyticsOverview): MetricCard[] {
  const { totals, streaks } = overview

  return [
    {
      label: 'User messages',
      value: formatCompact(totals.userMessages),
      detail: `${formatCompact(totals.userWords)} words written`,
      icon: <MessageSquare className="size-4" />,
    },
    {
      label: 'Assistant messages',
      value: formatCompact(totals.assistantMessages),
      detail: `${formatCompact(totals.assistantWords)} words generated`,
      icon: <Bot className="size-4" />,
    },
    {
      label: 'Sessions',
      value: formatCompact(totals.sessionsCreated),
      detail: `${formatCompact(totals.turnsCompleted)} turns completed`,
      icon: <Repeat2 className="size-4" />,
    },
    {
      label: 'Files changed',
      value: formatCompact(totals.filesChanged),
      detail: `${formatSignedInteger(totals.linesAdded)} / ${formatSignedInteger(-totals.linesDeleted)} lines`,
      icon: <FileDiff className="size-4" />,
    },
    {
      label: 'Approvals',
      value: formatCompact(totals.approvalRequests),
      detail: `${formatCompact(totals.inputRequests)} input requests`,
      icon: <MousePointerClick className="size-4" />,
    },
    {
      label: 'Attachments',
      value: formatCompact(totals.attachmentsSent),
      detail: `${formatCompact(totals.toolCalls)} tool calls`,
      icon: <Paperclip className="size-4" />,
    },
    {
      label: 'Current streak',
      value: `${formatInteger(streaks.current)}d`,
      detail: `${formatInteger(streaks.longest)}d longest`,
      icon: <CalendarDays className="size-4" />,
    },
    {
      label: 'Run health',
      value:
        totals.failedSessions > 0
          ? formatCompact(totals.failedSessions)
          : 'Clear',
      detail:
        totals.failedSessions > 0 ? 'failed sessions' : 'no failed sessions',
      icon:
        totals.failedSessions > 0 ? (
          <TerminalSquare className="size-4" />
        ) : (
          <Sparkles className="size-4" />
        ),
    },
  ]
}

function hasDailyActivity(overview: AnalyticsOverview): boolean {
  return overview.dailyActivity.some(
    (point) =>
      point.userMessages +
        point.assistantMessages +
        point.sessionsCreated +
        point.turnsCompleted >
      0,
  )
}

function hasConversationBalance(overview: AnalyticsOverview): boolean {
  return overview.conversationBalance.some(
    (point) => point.userWords + point.assistantWords > 0,
  )
}

function buildRecentDays(endDate: string, count: number): string[] {
  const end = new Date(`${endDate}T00:00:00`)
  return Array.from({ length: count }, (_, index) => {
    const date = new Date(end)
    date.setDate(end.getDate() - (count - 1 - index))
    return toDateKey(date)
  })
}

function findLatestActiveDay(activeDays: Set<string>): string | null {
  return [...activeDays].sort().at(-1) ?? null
}

function toDateKey(date: Date): string {
  const year = date.getFullYear()
  const month = `${date.getMonth() + 1}`.padStart(2, '0')
  const day = `${date.getDate()}`.padStart(2, '0')
  return `${year}-${month}-${day}`
}
